services:
  - type: web
    name: ladrillos-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: MONGODB_URI
        value: mongodb+srv://isleyterhualcaslopez:Hualcas%2B9734@cluster0.ir7hkwe.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
